// Code generated by hertz generator.

package bill_book

import (
	"context"

	bill_book "bill-book/biz/model/bill_book"
	api "bill-book/service/api"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateLedger .
// @router /api/v1/ledger/create [POST]
func CreateLedger(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.CreateLedgerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewLedgerService()
	resp, bizErr := s.CreateLedger(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetLedger .
// @router /api/v1/ledger/get [POST]
func GetLedger(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.GetLedgerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewLedgerService()
	resp, bizErr := s.GetLedger(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// UpdateLedger .
// @router /api/v1/ledger/update [POST]
func UpdateLedger(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.UpdateLedgerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewLedgerService()
	resp, bizErr := s.UpdateLedger(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// DeleteLedger .
// @router /api/v1/ledger/delete [POST]
func DeleteLedger(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.DeleteLedgerReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewLedgerService()
	resp, bizErr := s.DeleteLedger(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// ListLedgers .
// @router /api/v1/ledger/list [POST]
func ListLedgers(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.ListLedgersReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewLedgerService()
	resp, bizErr := s.ListLedgers(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// UpdateExchangeRates .
// @router /api/v1/exchange_rate/update [POST]
func UpdateExchangeRates(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.UpdateExchangeRatesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewLedgerService()
	resp, bizErr := s.UpdateExchangeRates(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// CreateParticipant .
// @router /api/v1/participant/create [POST]
func CreateParticipant(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.CreateParticipantReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewParticipantService()
	resp, bizErr := s.CreateParticipant(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// UpdateParticipant .
// @router /api/v1/participant/update [POST]
func UpdateParticipant(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.UpdateParticipantReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewParticipantService()
	resp, bizErr := s.UpdateParticipant(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// DeleteParticipant .
// @router /api/v1/participant/delete [POST]
func DeleteParticipant(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.DeleteParticipantReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewParticipantService()
	resp, bizErr := s.DeleteParticipant(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// CreateExpense .
// @router /api/v1/expense/create [POST]
func CreateExpense(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.CreateExpenseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewExpenseService()
	resp, bizErr := s.CreateExpense(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetExpense .
// @router /api/v1/expense/get [POST]
func GetExpense(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.GetExpenseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewExpenseService()
	resp, bizErr := s.GetExpense(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// UpdateExpense .
// @router /api/v1/expense/update [POST]
func UpdateExpense(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.UpdateExpenseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewExpenseService()
	resp, bizErr := s.UpdateExpense(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// DeleteExpense .
// @router /api/v1/expense/delete [POST]
func DeleteExpense(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.DeleteExpenseReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewExpenseService()
	resp, bizErr := s.DeleteExpense(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// ListExpenses .
// @router /api/v1/expense/list [POST]
func ListExpenses(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.ListExpensesReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewExpenseService()
	resp, bizErr := s.ListExpenses(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetSettlement .
// @router /api/v1/settlement/get [POST]
func GetSettlement(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.GetSettlementReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewSettlementService()
	resp, bizErr := s.GetSettlement(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetReport .
// @router /api/v1/report/get [POST]
func GetReport(ctx context.Context, c *app.RequestContext) {
	var err error
	var req bill_book.GetReportReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	s := api.NewReportService()
	resp, bizErr := s.GetReport(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
