// Code generated by hertz generator.

package main

import (
	"context"
	"embed"
	"path/filepath"
	"strings"

	"bill-book/conf"
	"bill-book/dal"
	"bill-book/logger"
	"bill-book/middleware"

	router "bill-book/biz/router"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/cors"
)

//go:embed web/dist
var buildFS embed.FS

//go:embed web/dist/index.html
var indexPage []byte

func main() {
	conf.Init()
	dal.Init()
	logger.Init(conf.GetConfig().Logger)

	h := server.Default(server.WithHostPorts(conf.GetConfig().Server.Port))
	h.Use(middleware.Trace(), recovery.Recovery(), cors.Default())

	router.GeneratedRegister(h)
	customizedRegister(h)
	staticFs(h)

	h.Spin()
}

func staticFs(h *server.Hertz) {
	// Root path returns the embedded index.html directly.
	h.GET("/", func(c context.Context, ctx *app.RequestContext) {
		ctx.Header("Content-Type", "text/html; charset=utf-8")
		ctx.Write(indexPage)
	})

	// Serve static assets under /assets from the embedded build output.
	h.GET("/assets/*filepath", func(c context.Context, ctx *app.RequestContext) {
		assetPath := ctx.Param("filepath")
		fsPath := filepath.Join("web/dist/assets", assetPath)

		content, err := buildFS.ReadFile(fsPath)
		if err != nil {
			ctx.SetStatusCode(consts.StatusNotFound)
			return
		}

		if strings.HasSuffix(assetPath, ".js") {
			ctx.Header("Content-Type", "application/javascript; charset=utf-8")
		} else if strings.HasSuffix(assetPath, ".css") {
			ctx.Header("Content-Type", "text/css; charset=utf-8")
		} else if strings.HasSuffix(assetPath, ".html") {
			ctx.Header("Content-Type", "text/html; charset=utf-8")
		}

		ctx.Write(content)
	})

	// SPA fallback for all other GET requests, excluding the /api prefix.
	h.GET("/*any", func(c context.Context, ctx *app.RequestContext) {
		path := string(ctx.Path())
		if strings.HasPrefix(path, "/api") {
			ctx.SetStatusCode(consts.StatusNotFound)
			return
		}
		ctx.Header("Content-Type", "text/html; charset=utf-8")
		ctx.Header("Cache-Control", "no-cache")
		ctx.Write(indexPage)
	})
}
