// Code generated by hertz generator.

package bill_book

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exchange_rateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateexchangeratesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _expenseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createexpenseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteexpenseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getexpenseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listexpensesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateexpenseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _ledgerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createledgerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteledgerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getledgerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listledgersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateledgerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _participantMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createparticipantMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteparticipantMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateparticipantMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getreportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _settlementMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsettlementMw() []app.HandlerFunc {
	// your code...
	return nil
}
