// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	bill_book "bill-book/biz/router/bill_book"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	bill_book.Register(r)
}
